apiVersion: v1
kind: Pod
metadata:
  name: fleetman-queue
  labels:
    app: fleetman-queue
    release: release1
spec:
  containers:
  - name: queue
    image: richardchesterwood/k8s-fleetman-queue:release1
